<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mhiremath-L" name="Test" tests="2" failures="1" timestamp="14 Feb 2020 18:10:35 GMT" time="6.498" errors="0">
  <testcase name="addressassignment" time="3.764" classname="com.api.testng.UsersApi.GetAPI"/>
  <testcase name="adddirectorynumber" time="2.718" classname="com.api.testng.UsersApi.PostAPI">
    <failure type="java.lang.AssertionError" message="expected [Succcess] but found [DB returned 23505]">
      <![CDATA[java.lang.AssertionError: expected [Succcess] but found [DB returned 23505]
	at com.api.testng.UsersApi.PostAPI.adddirectorynumber(PostAPI.java:42)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- adddirectorynumber -->
</testsuite> <!-- Test -->
